### ISSUE TITLE
build and push container image action fails most of the time

### ISSUE THREAD

**Issue by hanstrompert** [workfloworchestrator/orchestrator-core#376]
The `Build and push container image` action can fail because it needs the package build by the `Upload Python Package` action that might not be finished yet. Please fix this race condition.

**Comment by pboers1988** [comment]
Make the github action more robust. Perhaps allow 5 retries before actually failing.

**Comment by hanstrompert** [comment]
I believe you can also specify dependencies between workflows, something like the following could perhaps work?

```
on:
  workflow_run:
    workflows: ["Upload Python Packag"]
    types: 
      - completed
 ```
